// Code generated from HCNetSDK.h NET_DVR_* / NET_ERR_* / NET_SDK_ERR_* error
// constants (the ones returned by NET_DVR_GetLastError). Do not edit by hand -
// see scripts/vendor-sdk.* and the header for the authoritative source.
package hikvision

var errorMessages = map[uint32]string{
	0:   "No Error",
	1:   "Username or Password error",
	2:   "Don't have enough authority",
	3:   "have not Initialized",
	4:   "Channel number error",
	5:   "Number of clients connecting to DVR beyonds the Maximum",
	6:   "Version is not matched",
	7:   "Connect to server failed",
	8:   "Send data to server failed",
	9:   "Receive data from server failed",
	10:  "Receive data from server timeout",
	11:  "Transferred data has error",
	12:  "Wrong Sequence of invoking API",
	13:  "No such authority.",
	14:  "Execute command timeout",
	15:  "Serial port number error",
	16:  "Alarm port error",
	17:  "Parameters error",
	18:  "Server channel in error status",
	19:  "No hard disk",
	20:  "Hard disk number error",
	21:  "Server's hard disk is full",
	22:  "Server's hard disk error",
	23:  "Server doesn't support",
	24:  "Server is busy",
	25:  "Server modification failed",
	26:  "Input format of Password error",
	27:  "Hard disk is formating,  cannot execute.",
	28:  "DVR don't have enough resource",
	29:  "DVR Operation failed",
	30:  "Open PC audio failed",
	31:  "Server's talk channel is occupied",
	32:  "Time input is not correct",
	33:  "Can't playback the file that does not exist in Server",
	34:  "Create file error",
	35:  "Open file error",
	36:  "The previous operation is not finished yet",
	37:  "Get current playing time error",
	38:  "Playback error",
	39:  "Wrong file format",
	40:  "Wrong directory",
	41:  "Assign resource error",
	42:  "Audio card mode error",
	43:  "Buffer is too small",
	44:  "Create SOCKET error",
	45:  "Setup SOCKET error",
	46:  "Reach the maximum number",
	47:  "User does not exist",
	48:  "Write to FLASH error",
	49:  "DVR update failed",
	50:  "Decoding Card has been initialized already",
	51:  "Invoke API of player library error",
	52:  "Reach the maximum number of DVR Users",
	53:  "Failed to get Client software's IP or MAC address",
	54:  "No encoding on this channel",
	55:  "IP address is not matched",
	56:  "MAC address is not matched",
	57:  "Update file has wrong language",
	58:  "Reach the maximum player number",
	59:  "There is no enough space on the backup device",
	60:  "Failed to find the specified backup device",
	61:  "Image has wrong color bit,  24 color only",
	62:  "Image size exceeds the maximum value;  smaller than 128*256",
	63:  "Image file exceeds the maximum size;  smaller than 100K",
	64:  "Failed to load the player SDK from current directory",
	65:  "Failed to find the API's entry in player SDK",
	66:  "Failed to load the DSsdk from current directory",
	67:  "Failed to find the API's entry in DSsDK",
	68:  "Failed to involve the API of DSsDK.dll",
	69:  "Audio card has been occupied exclusively",
	70:  "Join to multicast group error",
	71:  "Failed to create log directory",
	72:  "Failed to bind socked error.",
	73:  "socket is disconnected,  that caused by network disconnected or unreachable destination mostly",
	74:  "User ID is using when logout",
	75:  "Socket listen error",
	76:  "Application error",
	77:  "Failed to write file",
	78:  "Forbidden to format read only disk",
	79:  "Same user name already exists.",
	80:  "Device Model is not matched when import parameters",
	81:  "Audio is not matched when import parameters",
	82:  "Software version is not matched when import parameters",
	83:  "IP Channels is off line when",
	84:  "Failed to load IPC communication library",
	85:  "Failed to load stream format convertion library",
	86:  "ip count overflow",
	87:  "add label or other operation reach the maximum number",
	88:  "Param Mode Error",
	89:  "Videoplat: CodeSpitter is Offline",
	90:  "Device is backuping",
	91:  "Channel doesn't support",
	92:  "The height line location is too concentrated, or the length line is not inclined enough",
	93:  "Cancel calibration conflict, if the rule and overall actual size filter have been set",
	94:  "Calibration point exceeds the range",
	95:  "The size filter does not meet the requirement",
	96:  "Device hasn't registered to ddns",
	97:  "DDNS inter error",
	98:  "This function don't support this OS.",
	99:  "Decode channel can not bind two or more display channel",
	100: "Failed to load the Intercom SDK from current directory",
	101: "NO Current UpdateFile",
	102: "user is not login yet",
	103: "it is using log switch file",
	104: "Port pool is exhaust",
	105: "The stream packet type is error",
	106: "IPID when IP access configuration is incorrect",
	107: "Load Preview COM Failed",
	108: "Load Voice talk COM Failed",
	109: "Load Alarm COM Failed",
	110: "Load Play back COM Failed",
	111: "Load Display COM Failed",
	112: "Load Industry COM Failed",
	113: "Load General config mgr COM Failed",
	114: "Load device core config COM Failed",
	115: "Load HCNetUtils Failed",
	121: "There is a mismatch between the component and core version",
	122: "There is a mismatch  between Live view component and core version.",
	123: "There is a mismatch  between voice component and core version",
	124: "There is a mismatch  between alarm component and core version",
	125: "There is a mismatch  between playback component and core version",
	126: "There is a mismatch  between display component and core version",
	127: "There is a mismatch  between industrial application component and core version",
	128: "There is a mismatch  between General configuration management component and the core version",
	136: "There is a mismatch  between Live view component and HCNetSDK version.",
	137: "There is a mismatch  between voice component and HCNetSDK version",
	138: "here is a mismatch  between alarm component and HCNetSDK version",
	139: "There is a mismatch  between playback component and HCNetSDK version",
	140: "There is a mismatch  between display component and HCNetSDK version",
	141: "There is a mismatch  between industrial application component and HCNetSDK version",
	142: "There is a mismatch  between General configuration management component and the HCNetSDK version",
	145: "import config file failed",
	146: "export config file failed",
	147: "certificate error.",
	148: "load lib ssl failed (maybe lib version unmatched)",
	149: "lib ssl version unmatched",
	150: "Alias is duplicate  //2011-08-31 the configuration of new ddns accessing device by alias or serial number",
	151: "Invalid Communication",
	152: "UserName is not exist",
	153: "UserName Locked",
	154: "Invalid User ID",
	155: "Low Login Version",
	156: "load libeay32.dll failed",
	157: "load ssleay32.dll failed",
	158: "load libiconv2 failed",
	159: "SSL connect failed",
	160: "Multicast's address is error",
	161: "NET_ERR_LOAD_ZLIB",
	162: "NET_ERR_OPENSSL_NO_INIT",
	164: "can not find the server",
	165: "fail connect with test server",
	166: "NAS server mount fail,invalid directory",
	167: "NAS server mount fail,no authority",
	168: "sever not configure DNS.",
	169: "Email server not configure gateway",
	170: "the password of the test server is error",
	171: "device connect exception with smtp server",
	172: "FTP server create directory fail",
	173: "FTP server not have write authority",
	174: "IP conflict",
	175: "No free space for the storage pool",
	176: "The storage pool of the cloud server is invalid, no configured storage pool or the storage pool ID is incorrect.",
	177: "Effectiveness Reboot",
	178: "ANR arming is already established.",
	179: "Upload Link is already established.",
	180: "Incorrect file format",
	181: "Incorrect file content",
	182: "HRUDP limit the number of connections over equipment",
	183: "access or secret key is error",
	184: "create port-multiplexing fail",
	185: "nonblocking capture picture not support",
	186: "already open asyncronous function,this function has been invalid",
	187: "alread reach to the max num of port-multiplexing",
	188: "invalid link or link has not been created",
	189: "interface not support ISAPI",
	251: "risk password",
	401: "no authoration: when server return 401,RTSP return it.",
	402: "fail to alloc resource",
	403: "parameter error.",
	404: "can't find the url. when server return 404,RTSP return it.",
	406: "user force to stop.",
	407: "rtsp get port failed",
	410: "rtsp describe communicate error",
	411: "Sending signal \"DECRIBE\" is timeout",
	412: "Failed to send signal \"DECRIBE\"",
	413: "Receiving signal \"DECRIBE\" is timeout",
	414: "Receiving data of signal \"DECRIBE\" error",
	415: "Failed to receive signal \"DECRIBE\"",
	416: "Signal \"DECRIBE\" server returns the error",
	420: "rtsp setup communicate error",
	421: "Sending signal \"SETUP\" is timeout",
	422: "Sending signal \"SETUP\" error",
	423: "Receiving signal \"SETUP\" is timeout",
	424: "Receiving data of signal \"SETUP\" error",
	425: "Failed to receive signal \"SETUP\"",
	426: "It exceeds the max connection number, or no enough resource. when server return 453,RTSP return it.",
	427: "Signal \"SETUP\" server returns the error",
	430: "rtsp play communicate error",
	431: "Sending signal \"PLAY\" is timeout",
	432: "Sending signal \"PLAY\" error",
	433: "Receiving signal \"PLAY\" is timeout",
	434: "Receiving data of signal \"PLAY\" error",
	435: "Failed to receive signal \"PLAY\"",
	436: "Signal \"PLAY\" server returns the error",
	440: "rtsp teardown communicate error",
	441: "Sending signal \"TEARDOWN\" is timeout",
	442: "Sending signal \"TEARDOWN\" error",
	443: "Receiving signal \"TEARDOWN\" is timeout",
	444: "Receiving data of signal \"TEARDOWN\" error",
	445: "Failed to receive signal \"TEARDOWN\"",
	446: "Signal \"TEARDOWN\" server returns the error",
}
